rules:
  confidence_threshold: 80
  dicom_tags:
  - name: Patient's Name
    tag:
    - 0x10
    - 0x10
  - name: Patient ID
    tag:
    - 0x10
    - 0x20
  - name: Patient's Sex
    tag:
    - 0x10
    - 0x30
  - name: Patient's Age
    tag:
    - 0x10
    - 0x1010
  - name: Patient's Size
    tag:
    - 0x10
    - 0x1020
  - name: Patient's Weight
    tag:
    - 0x10
    - 0x1030
  - name: Patient's Insurance Plan
    tag:
    - 0x10
    - 0x1060
  - name: Patient's Relationship Status
    tag:
    - 0x10
    - 0x1070
  - name: Other Patient IDs
    tag:
    - 0x10
    - 0x1000
  - name: Other Patient Names
    tag:
    - 0x10
    - 0x1001
  - name: Study Instance UID
    tag:
    - 0x20
    - 0xD
  - name: Study ID
    tag:
    - 0x20
    - 0x10
  - name: Series Instance UID
    tag:
    - 0x20
    - 0xE
  - name: SOP Instance UID
    tag:
    - 0x8
    - 0x18
  - name: Frame of Reference UID
    tag:
    - 0x20
    - 0x52
  - name: Reference SOP Instance UID
    tag:
    - 0x8
    - 0x1155
  - name: Institution Name
    tag:
    - 0x8
    - 0x80
  - name: Private tag data
    tag:
    - 0x13
    - 0x1013
  - name: UID
    tag:
    - 0x40
    - 0xA124
  - name: Storage Media File-set UID
    tag:
    - 0x88
    - 0x140
  - name: Instance Creator UID
    tag:
    - 0x8
    - 0x14
  - name: Study Date
    tag:
    - 0x8
    - 0x20
  - name: Series Date
    tag:
    - 0x8
    - 0x21
  - name: Acquisition Date
    tag:
    - 0x8
    - 0x22
  - name: Content Date
    tag:
    - 0x8
    - 0x23
  - name: Series Time
    tag:
    - 0x8
    - 0x31
  - name: Acquisition Time
    tag:
    - 0x8
    - 0x32
  - name: Content Time
    tag:
    - 0x8
    - 0x33
  - name: Accession Number
    tag:
    - 0x8
    - 0x50
  - name: Secondary Capture Device ID
    tag:
    - 0x18
    - 0x1010
  - name: Date of Secondary Capture
    tag:
    - 0x18
    - 0x1012
  - name: Time of Secondary Capture
    tag:
    - 0x18
    - 0x1014
  - name: Secondary Capture Device Software Versions
    tag:
    - 0x18
    - 0x1019
  - name: Synchronization Frame of Reference UID
    tag:
    - 0x20
    - 0x200
  - name: Referenced Frame of Reference UID
    tag:
    - 0x3006
    - 0x24
  - name: Related Frame of Reference UID
    tag:
    - 0x3006
    - 0xC2
  - name: Study Time
    tag:
    - 0x8
    - 0x30
  keywords:
  - Address
  - Telephone Numbers
  - Fax Numbers
  regex:
  - '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}'
  - \d{3}-\d{2}-\d{4}
  - d{2}/\d{2}/\d{4}
  - \d{2}.\d{2}.\d{4}
  - \d{2}-\d{2}-\d{4}
  - \d{3}[-.\s]?d{7}
  - \d{3}[-.\s]?\d{3}[-.\s]?\d{4}
  - \(\d{3}\)[\s]?\d{3}-\d{4}
  - \d{5}(?:[-\s]\d{4})?
  vr:
  - PN
